`timescale 1ns / 1ps

module tb_baseline;

    // Inputs
    reg signed [7:0] a;
    reg signed [7:0] b;

    // Outputs
    wire signed [15:0] p;

    // Instantiate the Unit Under Test (UUT)
    baseline_mac uut (
        .a(a),
        .b(b),
        .p(p)
    );

    // File handling variables
    integer file, r;
    reg [31:0] mode; 
    reg [31:0] expected_out;
    integer error_count;
    integer test_count;

    initial begin
        // REQUIRED FOR EDA PLAYGROUND: Dumps the data so you can see the waveform
        $dumpfile("dump.vcd");
        $dumpvars(0, tb_baseline);

        // Initialize Variables
        a = 0;
        b = 0;
        error_count = 0;
        test_count = 0;

        // Open the golden math file generated by your Python script
        file = $fopen("test_vectors.txt", "r");
        if (file == 0) begin
            $display("ERROR: Could not open test_vectors.txt");
            $finish;
        end

        $display("--- Starting Baseline MAC Verification ---");

        // Read the file line by line
        // Format from Python: Mode A B Expected_Out
        while (!$feof(file)) begin
            r = $fscanf(file, "%d %h %h %h\n", mode, a, b, expected_out);
            
            // If it successfully read all 4 items
            if (r == 4) begin
                // The baseline MAC only does standard INT8, so only test Mode 0
                if (mode == 0) begin
                    test_count = test_count + 1;
                    #10; // Wait 10ns for the math to happen
                    
                    // Check if the hardware output matches the Python output
                    if (p !== expected_out) begin
                        $display("FAIL: A=%h, B=%h | Expected=%h, Got=%h", a, b, expected_out, p);
                        error_count = error_count + 1;
                    end else begin
                        $display("PASS: A=%h, B=%h | Out=%h", a, b, p);
                    end
                end
            end
        end

        $fclose(file);

        $display("-----------------------------");
        $display("Total Mode 0 Tests: %d", test_count);
        $display("Total Errors: %d", error_count);
        
        if (error_count == 0 && test_count > 0)
            $display(">>> SUCCESS: Day 3 Verification Passed! <<<");
        else
            $display(">>> FAILED: Check your logic. <<<");

        $finish;
    end

endmodule
